name: khatwa_client
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_bloc:
  flutter_svg:
  fluttertoast:
  go_router:
  shared_preferences:
  cached_network_image:
  image_picker:
  url_launcher:
  easy_localization: ^3.0.7
  share:
  icons_launcher: ^3.0.0
  intl_phone_field: ^3.2.0
  lottie: ^3.1.2
  easy_rich_text: ^2.1.0
  flutter_dotenv: ^5.1.0
  mobkit_dashed_border: ^0.0.6
  timeago: ^3.7.0
  supabase_flutter: ^2.5.1
  loading_animation_widget:
  gap: ^3.0.1
  audioplayers: ^6.1.0
  just_audio: ^0.9.40
  flutter_cached_pdfview: ^0.4.2
  syncfusion_flutter_gauges: ^27.1.48
  flutter_animate: ^4.5.0
  #________________________OLD VERSION
  carousel_slider_plus: ^7.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.5.0
  firebase_messaging: ^15.1.2

  flutter_image_compress: ^2.1.0
  flutter_polyline_points: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.5.0
  google_places_autocomplete_text_field: ^0.1.3
  google_places_flutter: ^2.0.9

  persistent_bottom_nav_bar: ^6.2.1
  rating_dialog: ^2.0.4
  socket_io_client: ^2.0.3+1

  video_player: ^2.3.0
  #win32: ^5.5.4
  youtube_player_flutter: ^9.0.4
  animated_snack_bar: ^0.4.0
  awesome_dialog: ^3.1.0
  cloud_firestore: null
  #cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.3.2
  #device_preview: ^1.1.0
  equatable: ^2.0.5
  #sqflite:
  #multiple_images_picker: ^1.0.1
  #firebase_auth: ^4.9.0
  #firebase_core: ^2.15.1
  firebase_auth: ^5.3.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.9
  #flutter_facebook_auth: null
  get: ^4.6.5
  get_it: ^8.0.0
  #google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  googleapis_auth: ^1.6.0
  webview_flutter: ^4.4.2
  adaptive_theme: ^3.6.0
  conditional_builder_null_safety: ^0.0.6
  flutter_spinkit: ^5.2.1
  otp_timer_button: ^1.1.1
  flutter_otp_text_field: ^1.2.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "new_assets/app_icon/ic_launcher.png"
  platforms:
    android:
      enable: true
      image_path: "new_assets/app_icon/ic_launcher.png"
      notification_image: "new_assets/app_icon/ic_launcher.png"
      # adaptive_background_color: '#182633'
      adaptive_background_image: "assets/image/ic_launcher_background.png"
      adaptive_foreground_image: "new_assets/app_icon/ic_launcher_foreground.png"
      adaptive_round_image: "new_assets/app_icon/ic_launcher.png"
      adaptive_monochrome_image: "new_assets/app_icon/ic_launcher_monochrome.png"
    ios:
      enable: true
      image_path: "assets/image/ic_launcher.png"
      # For iOS 18+ (support dark and tinted)
      dark_path: "assets/image/ic_launcher.png"
      tinted_path: "assets/image/ic_launcher.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo2.jpeg"
  min_sdk_android: 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - new_assets/
    - new_assets/images/
    - new_assets/app_icon/
    - new_assets/fonts/
    - new_assets/fonts/Rubik/
    - new_assets/fonts/Rubik/static/
    - new_assets/translations/

  fonts:
    - family: Rubik
      fonts:
        - asset: new_assets/fonts/Rubik/static/Rubik-Light.ttf
          weight: 300
        - asset: new_assets/fonts/Rubik/static/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-Regular.ttf
          weight: 400
        - asset: new_assets/fonts/Rubik/static/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-Medium.ttf
          weight: 500
        - asset: new_assets/fonts/Rubik/static/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-SemiBold.ttf
          weight: 600
        - asset: new_assets/fonts/Rubik/static/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
        - asset: new_assets/fonts/Rubik/static/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-ExtraBold.ttf
          weight: 800
        - asset: new_assets/fonts/Rubik/static/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: new_assets/fonts/Rubik/static/Rubik-Black.ttf
          weight: 900
        - asset: new_assets/fonts/Rubik/static/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
